### ISSUE TITLE
TypeError in Frame.from_records when records are ints with None

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#105]
```python
sf.Frame.from_records([
    (88,),
    (27, ),
    (27,),
    (None,)])
```
Produces:

> builtins.TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by flexatone** [comment]
Thanks for isolating this case!

This issue is due to the handling of the type induction SF tries to do to optimize `np.array` construction. Note that when using `Frame.from_records`, supplying a `dtypes` will improve performance and (prior to this fix) avoid this issue. 

This fix will be in the 0.4.1 release.
