### ISSUE TITLE
Frame.to_msgpack, Frame.from_msgpack

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#116]

**Comment by MadisonAster** [comment]
I built a small use case to play with using yfinance since you're testing numpy datatypes in your unittests.
I have a rough draft now that also makes use of msgpack_numpy to handle the extra types.
Still need to figure out a way to insert the type information into the returned msgpack so I can write from_msgpack

Let me know if I'm on the right track here or if I'm diverging from what you had in mind.
[Here's my branch](https://github.com/MadisonAster/static-frame/commits/116/msgpack).

Cheers.

**Comment by flexatone** [comment]
Thank you for looking at this. Yes, this looks like a good start. Please create a PR (when you are ready) so I can offer more comments.
