### ISSUE TITLE
FrameGO/IndexHierarchyGO: request for symmetry between column insertion and retrieval

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#159]
I'd like to propose applying the same constraints to key insertion as are applied to key lookup (i.e., `HLoc`).

Currently, given:
```python
f = sf.FrameGO.from_dict({('A', 1): (10, 20), ('A', 2): (40, 50), ('B', 1): (30, 50)})
f = f.relabel(columns=sf.IndexHierarchyGO.from_labels(f.columns))
key = ('B', 2)
```

`key` can be used to add to the frame,

```python
f[key] = 5
<FrameGO>
<IndexHierarchyGO> A       A       B       B       <object>
                   1       2       1       2       <object>
<Index>
0                  10      40      30      5
1                  20      50      50      5
<int64>            <int64> <int64> <int64> <int64>
```
but not to extract the added value:

```python
print(f'Added {f[key]}') 
# builtins.KeyError: '__getitem__ does not support multiple indexers'
```

likewise, selecting using an arbitrary column works on a Frame with single level columns, but not IndexHierarchy columns:

```python
f[f.columns[0]] 
# builtins.KeyError: '__getitem__ does not support multiple indexers'
```

I think this behaviour is surprising. It's the only case I'm aware of in python where the key used to set a value cannot be used to retrieve it. 

Indexing in a table data structure is complex, as you've [demonstrated](https://www.youtube.com/watch?v=xX8tXSNDpmE&feature=youtu.be), but I think there is value in keeping consistency between key insertion and retrieval. 

You've argued that unlike `__getitem__`, the `__setitem__` case is unambiguous. However, I think that there is some ambiguity in this case as well; a user may be expecting to add a column named with a literal tuple, (perhaps not realizing that their column index is a hierarchy). From a user perspective, it appears that SF is silently converting the key to an HLoc when the frame assigned to has hierarchical columns. 

I think it's clearer to always require HLocs when interacting with IndexHierarchy.

**Comment by flexatone** [comment]
Thank you for isolating this inconsistency.

I believe the best course of action, however, is not to require HLocs for every interaction with IndexHieararchy, but to instead simply remove the restriction on tuples given to `Frame.__getitem__`. This is not what you suggested, but achieves the desired symmetry and solves some other problems that had not yet been addressed.

First: The prohibition of tuples to  `Frame.__getitem__` was part of the goal of asserting that  `Frame.__getitem__` should only ever do columns selection, as opposed to `loc`, `iloc` selectors, which treat tuples as specifying a row selection and a column selection. Not accepting tuples, however, is an independent consideration of how that tuple is used;  the implementation of  `Frame.__getitem__` simply does not need to ever treat the passed key as a row selector to achieve the desired goal.

The prohibition of tuples in  `Frame.__getitem__` selections amusingly (and undesirably) made it impossible to select single column, as a `Series`, from a Frame with a 1D index of tuples:

```python
>>> f = sf.Frame(np.arange(8).reshape(2,4), columns=tuple(sf.IndexHierarchy.from_product(('I', 'II'), ('A', 'B'))))
>>> f
<Frame>
<Index> ('I', 'A') ('I', 'B') ('II', 'A') ('II', 'B') <object>
<Index>
0       0          1          2           3
1       4          5          6           7
<int64> <int64>    <int64>    <int64>     <int64>

>>> f[('I', 'B')]
Traceback (most recent call last):
KeyError: '__getitem__ does not support multiple indexers'
```

Second: I am fairly convinced of the desirability of permitting tuples to be  used as leaf-node selections of IndexHierarchy, rather than always requiring HLocs. Recall that HLoc are designed to handle partial-depth selection, as well as selection with slices and selection lists. HLocs can also fully specify a single label (a leaf node). And yet, the true "label" in the IndexHiearchy is not an HLoc: it can only be leaf-node selection, but can never be a more general selection. While HLocs can select a single label, the label is not an HLoc.

If we iterate an Index, we iterate over its hashable labels; if we iterate an IndexHierarchy, it is natural to iterate over hashable labels, and tuples again are a practical choice. Now, this is not how the IndexHierarchy is implemented, but it is a sensible approach.

So as shown below (and implemented for some time now), HLocs can be used for multiple and single-label selection; tuples can be used to explicitly select a single label. 

```python
>>> f = sf.Frame(np.arange(8).reshape(2,4), columns=sf.IndexHierarchy.from_product(('I', 'II'), ('A', 'B')))
>>> f
<Frame>
<IndexHierarchy> I       I       II      II      <<U2>
                 A       B       A       B       <<U2>
<Index>
0                0       1       2       3
1                4       5       6       7
<int64>          <int64> <int64> <int64> <int64>

>>> f.loc[:, sf.HLoc[:, 'A']]
<Frame>
<IndexHierarchy> I       II      <<U2>
                 A       A       <<U2>
<Index>
0                0       2
1                4       6
<int64>          <int64> <int64>

>>> f.loc[:, sf.HLoc['II', 'A']]
<Series: ('II', 'A')>
<Index>
0                     2
1                     6
<int64>               <int64>

>>> f.loc[:, ('II', 'A')]
<Series: ('II', 'A')>
<Index>
0                     2
1                     6
<int64>               <int64>

>>> f.loc[:, f.columns[2]]
<Series: ('II', 'A')>
<Index>
0                     2
1                     6
<int64>               <int64>
```

That this suggests that an IndexHierachy is like a 1D index of tuples is intentional and desirable. With this design, we can easily translate between the two,  and there are contexts when it might be efficient or necessary for users to do so. There are other benefits of this connection in reindexing and concatenation that, for space, I will not go into here.

```python
>>> f1 = sf.Frame(np.arange(8).reshape(2,4), columns=sf.IndexHierarchy.from_product(('I', 'II'), ('A', 'B')))
>>> f1
<Frame>
<IndexHierarchy> I       I       II      II      <<U2>
                 A       B       A       B       <<U2>
<Index>
0                0       1       2       3
1                4       5       6       7
<int64>          <int64> <int64> <int64> <int64>

>>> f1.relabel_flat(columns=True)
<Frame>
<Index> ('I', 'A') ('I', 'B') ('II', 'A') ('II', 'B') <object>
<Index>
0       0          1          2           3
1       4          5          6           7
<int64> <int64>    <int64>    <int64>     <int64>

>>> f2 = f1.relabel(columns=iter(f.columns))
>>> f2
<Frame>
<Index> ('I', 'A') ('I', 'B') ('II', 'A') ('II', 'B') <object>
<Index>
0       0          1          2           3
1       4          5          6           7
<int64> <int64>    <int64>    <int64>     <int64>

>>> f3 = f2.relabel(columns=sf.IndexHierarchy.from_labels(f2.columns))
>>> f3
<Frame>
<IndexHierarchy> I       I       II      II      <<U2>
                 A       B       A       B       <<U2>
<Index>
0                0       1       2       3
1                4       5       6       7
<int64>          <int64> <int64> <int64> <int64>
```

Third: returning to your original observation: I fully agree that a key used to set a value should be able to retrieve it. As suggested above, this can be supported simply by removing the prohibition on tuples in `Frame.__getitem__`. By doing this we become consistent in the other ways that a leaf-node selection can be either a tuple or a fully-specified HLoc.

With this and a few related changes, we can set and get  with leaf-node selections using either tuples or HLoc:

```python
>>> f = sf.FrameGO(np.arange(8).reshape(2,4), columns=sf.IndexHierarchy.from_product(('I', 'II'), ('A', 'B')))
>>> f
<FrameGO>
<IndexHierarchyGO> I       I       II      II      <<U2>
                   A       B       A       B       <<U2>
<Index>
0                  0       1       2       3
1                  4       5       6       7
<int64>            <int64> <int64> <int64> <int64>

>>> f[('III', 'A')] = False

>>> f[sf.HLoc['III', 'B']] = True

>>> f[('III', 'A')]
<Series: ('III', 'A')>
<Index>
0                      False
1                      False
<int64>                <bool>

>>> f[sf.HLoc['III', 'B']]
<Series: ('III', 'B')>
<Index>
0                      True
1                      True
<int64>                <bool>
```

And we can also now retrieve columns from 1D indices that have tuples as labels, making the getitem selection consistent with `loc` selection:

```python
>>> f = sf.FrameGO(np.arange(8).reshape(2,4), columns=tuple(sf.IndexHierarchy.from_product(('I', 'II'), ('A', 'B'))))
>>> f
<FrameGO>
<IndexGO> ('I', 'A') ('I', 'B') ('II', 'A') ('II', 'B') <object>
<Index>
0         0          1          2           3
1         4          5          6           7
<int64>   <int64>    <int64>    <int64>     <int64>

>>> f[('I', 'B')]
<Series: ('I', 'B')>
<Index>
0                    1
1                    5
<int64>              <int64>

>>> f.loc[:, ('I', 'B')]
<Series: ('I', 'B')>
<Index>
0                    1
1                    5
<int64>              <int64>
```

Thanks again for isolating this issue. With these changes (to be released in 0.6), we achieve symmetry and increase overall consistency.
