### ISSUE TITLE
Make values a proper method.

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#161]
@flexatone I know I have mentioned it casually before, but just to make a formal request before SF goes stable: I think `values` should be a method on all structures.

SF is good about being dictionary-like in many ways (to the point of aliasing `__getitem__` and `loc` on `Series`), but this is one pretty glaring exception. I think that it would be natural for `values` (like `keys` and `items`) to be called, **especially since it is already a property on everything except `Series`**. If we might do re-caching work under-the-hood anyways for this "attribute lookup", we might as well be transparent about it, while reinforcing our dict-like interface.

(Also, for what it's worth, it looks like calling a method is about 5% faster than accessing a property.)

Not a huge deal, but it's always struck me as a bit of a wart!

**Comment by flexatone** [comment]
While I appreciate the desire for SF containers to be as dict-like as possible, the convention that Pandas and xarray have established, i.e., using `.values` instead of `.values()`,  is extremely well established. It might be a wart, but I do not see much benefit in deviating from the convention in this case.

In general, I think `.values` is only really useful from `Series`, and in that case, it literally is a direct reference to the underlying (immutable) array. I am not sure that there is much benefit in being "transparent" that the usage of `.values` on other containers is a property.

What other benefits, other than consistency with dictionary-like interfaces and possibly some small performance benefit, would `values`-as-a method provide?

**Comment by brandtbucher** [comment]
The only reason I could see for changing the interface is consistency with `dict`. But if we have concerns for _other_ consistencies, as you've mentioned, then the status quo wins a stalemate.
