### ISSUE TITLE
Interfaces for providing fill_value in reindexing that minimize type coercions

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#177]
```python
import numpy as np
import static_frame as sf

a = np.array([datetime.date.today()]).astype(np.dtype('datetime64[ns]'))
# array(['2020-02-28T00:00:00.000000000'], dtype='datetime64[ns]')

b = sf.Series(a)
# <Series>
# <Index>
# 0        2020-02-28T00:00:...
# <int64>  <datetime64[ns]>

c = b.reindex([0, 1])
# <Series>
# <Index>
# 0        1582848000000000000
# 1        nan
# <int64>  <object>

```

As you can see, the dtype of the reindexed series has changed. Maybe because the reindex introduces a `nan` (rather than `NaT`)?

**Comment by flexatone** [comment]
Thank you for posting this issue.

The primary issue here is how NP handles converting datetime64 to object, where for MS and greater datetime64 types, a datetime object is returned; but for NS and lower types, an integer (presumably steps from the epoch) is returned.

```python
>>> a1 = np.array([datetime.date.today()]).astype(np.dtype('datetime64[ns]'))
>>> a1.tolist()
[1582848000000000000]
>>> a2 = np.array([datetime.date.today()]).astype(np.dtype('datetime64[ms]'))
>>> a2.tolist()
[datetime.datetime(2020, 2, 28, 0, 0)]
```
In your example, you reindex introduces a NaN, and forces the value array to object. As you suggest, if you explicitly provide a NaT, your types is retained:

```python
>>> sf.Series(a1).reindex([0, 1], fill_value=np.datetime64('nat'))
<Series>
<Index>
0        2020-02-28T00:00:...
1        NaT
<int64>  <datetime64[ns]>
```

**Comment by ForeverWintr** [comment]
Thanks for the explanation. The approach of specifying a fill value works in this case, but what If I have a Frame containing columns with different dtypes? This suggests a single `fill_value` argument to `Frame.reindex` may be insufficient. 

It seems desirable for StaticFrame to be able to choose a default fill value that doesn't result in type conversion.

**Comment by ForeverWintr** [comment]
I've tried downcasting the timestamp to `'datetime64[D]'`, but this causes the dates to be converted to python `datetime.date` objects on reindex, which is also unexpected:

```python
d = b.astype(np.dtype('datetime64[D]'))
d.reindex([0, 1])
<Series>
<Index>
0        2020-02-28
1        nan
<int64>  <object>
```

**Comment by flexatone** [comment]
As before, this is because the default `fill_value` is forcing the entire column to object type; if you set `fill_value` to `np.datetime64('nat')`, you will get the expected result.

**Comment by ForeverWintr** [comment]
Actually, I realize that reindexing any series/frame of dtype other than float will result in a new dtype if the new index doesn't align perfectly and you don't explicitly provide a fill value. Is this desired? It seems like it could introduce hard to diagnose bugs, as code that reindexes can't rely on a consistent dtype.

```python
sf.Series(list('ab')).reindex([0, 1,])
<Series>
<Index>
0        a
1        b
<int64>  <<U1>

sf.Series(list('ab')).reindex([0, 1, 2])
<Series>
<Index>
0        a
1        b
2        nan
<int64>  <object>

```

**Comment by ForeverWintr** [comment]
> As before, this is because the default `fill_value` is forcing the entire column to object type; if you set `fill_value` to `np.datetime64('nat')`, you will get the expected result.

Yes, but as I stated, passing fill value isn't sufficient if you're reindexing a `Frame`.

**Comment by flexatone** [comment]
There is no danger of inconsistency or hard to diagnose bugs, as the logic for determining compatible types is deterministic and well defined. Of course, the `fill_value` you provide, whether accepting the default or otherwise, affects the final result. 

Supplying multiple, per-column `fill_value` when reindexing a `Frame` might be possible, but it does make that parameter more complex. I suppose something like what we accept for `dtypes` arguments might be possible.  Please create a new issue for this, and I can explore the implementation. 

Automatically supplying a fill value that does not change the dytpe is problematic. For example, if reindexing a Boolean Series, it is not obvious if newly introduced labels should be True or False values. 

Finally, the dtype of a `Series` is always known!

**Comment by ForeverWintr** [comment]
Having just spent hours diagnosing a bug caused by this issue, I disagree that there's no danger of hard to diagnose bugs. Further, although of course the dtype of a Series is always known *eventually*, it is often not known at time of writing code; consider the case where you're writing a function that receives a Frame/Series.

Your point that it's not always possible to determine a fill value that doesn't change dtype is well taken though (at least until SF moves to using a mask for missing data!). A better request on my part is for StaticFrame to automatically select a fill value that results in 'the best' type conversion, i.e., does not change the duck-type of the underlying data, and preserves vectorizability where possible. In the case of `bool`, I think `nan` and `None` are equally acceptable, as decomposition to python's `bool` is probably the best we can do. For dates and timestamps, `nat` should probably be chosen. I'm not sure about other cases. 

The logic for determining compatible types may be deterministic and well defined, but it's also completely opaque to a user of the library. Requiring users to supply the appropriate fill value will mean requiring them to deduce their own mapping from dtype to fill value, and they're likely to make mistakes in that mapping. 

Better I think is to have StaticFrame define a default, correct mapping of dtype to fill value once so that users of the library don't have to.

**Comment by flexatone** [comment]
Apologies for underestimating the burden you may have faced in handling issues caused by this behavior. 

That said, I think you may not be considering some of the possible negative outcomes of automatically choosing a "correct" `fill_value`. For example, reindexing a Boolean `Series` with a `nan` or `None` `fill_value` will force the creation of an `object` array, causing a significant degradation in performance compared to a Boolean array, permit more than two possible values, and disable the opportunity for Boolean selection in `loc` and `iloc` selection. 

While it is clear that, for a `datetime64` array, the best fill value is always `NaT`, for unicode arrays is `None`, `nan`, or `''` the best choice? The implications of this choice are significant and can lead to diverse downstream outcomes. Doing this automatically for all dtypes is, I feel, undesirable, and more opinionated than we want SF to be. I do not think there is a "correct" option available for all possible dtypes that will satisfy all scenarios.

I see your point, however, that users may not be able to easily understand the implication of various `fill_value` arguments on the resultant dtype. Here are some options I see:

1. Permit per-column `fill_value` specification with `Frame.reindex` and related operations. This will at least permit getting the desired result in one function call when a `Frame` has heterogeneous columnar types.
2. Expose a public utility function that, given a dtype, returns a reasonable default per dtype that does not force undesirable type coercion (even if it forces going to an object dtype).
3. Consider a special type (like `FillValueAuto`) that, if given as an argument to `fill_value`, uses (2) for each columnar type. This would be similar to how `IndexAutoFactory` works when given to an `index` or `columns` argument. 

Of these, (2) and (3) are likely the most easily implemented in the near term. 

I appreciate your ongoing thoughts and feedback on these issues!

**Comment by ForeverWintr** [comment]
I think 2 and 3 are basically what I'm arguing for. Once implemented, the default value to `reindex` and other methods that may introduce missing values can be `FillValueAuto`. IMO, this strikes a good balance between reasonable default and flexibility for customization when necessary.

**Comment by flexatone** [comment]
Agreed, thanks.

We know that for np.datetime64 we want the `FillValueAuto` to be NaT. For object dtypes, None. For string dtypes, do you think an empty string is the correct choice?

**Comment by ForeverWintr** [comment]
That's a hard question. What are the consequences of using `None` for string dtypes? I realize it means decomposing to an object dtype, but I'm not sure the downsides of that.

I can't really think of any downsides of using `''` either.

If we do pick `''`, is there any concern that we may fall victim to numpy's proclivity for truncating strings longer than its selected dtype?

e.g.,
```python
a = np.array(['', ''])
a[0] = 'asdf'
a
array(['a', ''], dtype='<U1')
```
