### ISSUE TITLE
Extend Bus.from_frames() to take optional index argument

### ISSUE THREAD

**Issue by nekobon** [InvestmentSystems/static-frame#255]
Currently `Bus.from_frames` constructor uses `frame.name` as its index value. Since `Frame.name` can only be a string, this Bus's index can only be string dtype.

For example, I have datetimme64 to their corresponding frame. I convert them to string to use them as their names.

```python
def gen_frame():
    for date, frame in gen_date_and_frame(): # yields datetime64 and a Frame
        yield frame.rename(str(date)) # name cannot be datetime64

sf.Bus.from_frames(gen_frame())

<Bus>
<Index>
2020-01-31 Frame
2020-02-29 Frame
2020-03-31 Frame
2020-04-30 Frame
2020-05-31 Frame
<<U10>     <object>
```

I think it would be nice to support an explicit `index` argument in `Bus.from_frames` so that we can have different Index types.

```python
dates, frames = zip(*gen_date_and_frame())
sf.Bus.from_frames(frames, index=dates) # I wish we could to this 

<Bus>
<IndexDate>
2020-01-31          Frame
2020-02-29          Frame
2020-03-31          Frame
2020-04-30          Frame
2020-05-31          Frame
<datetime64[D]>     <object>
```

**Comment by flexatone** [comment]
Thanks for this request.

While, in general, `name` attributes on SF containers can be any hashable, the `Bus` constrains contained `Frame` labels (and thus the `Index` of the `Bus`) to be strings. The reason for this constraint is that all storage formats used by the `Bus` ultimately need to store the label of the `Frame` with a string: for example, the names of sheets in an XLSX or the name of tables in an SQLite or HDF5. Rather than form a string from any hashable implicitly (and perhaps surprisingly), users must explicitly provide string labels.

Note also that other `from_frames` interfaces in SF only take `Frame`s and always use the `name` attribute as the label, which is the approach taken here. To provide `Frame`s and `Index` independently to a `Bus`, you can construct a `Series` of `Frame` and pass that to the default `Bus` constructor.

```python
>>> f1 = sf.Frame(np.arange(4).reshape(2, 2))
>>> sf.Bus(sf.Series((f1, f1), index=('a', 'b'), dtype=object))
<Bus>
<Index>
a       Frame
b       Frame
<<U1>   <object>
```

**Comment by nekobon** [comment]
That makes sense. I was initially using it to bundle up Frames rather than for I/O purpose, but I understand that it is a necessary restriction for serializing the data. Thank you!
