### ISSUE TITLE
test_frame_to_clipboard_a import of Tk crashes with SIGABRT on MacOS 11.1

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#295]
Apparently tkinter has issues on my version of macos, and [instantiating `Tk` causes a `SIGABRT`](https://bugs.python.org/issue42480).

```
Python 3.8.6 (default, Oct 27 2020, 08:57:44) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter as tk
>>> tk.Tk()
macOS 11 or later required !
fish: 'python' terminated by signal SIGABRT (Abort)
```

This in turn means that the `Frame` unittests can't run, because [`test_frame_to_clipboard_a`](https://github.com/InvestmentSystems/static-frame/blob/0af57554add99158b12547bb625aa4d96f7592a4/static_frame/test/unit/test_frame.py#L6597) crashes python. I think this test is a little problematic anyway, as it looks like it will clobber the user's clipboard when it works. Can we skip it/mock the actual clipboard behavior?

**Comment by flexatone** [comment]
Thanks for identifying this issue. Our integration testing is testing against MacOS-10.15 via a GitHub workflow, so we have not seen this issue yet.

I agree that clobbering a user's clipboard is a undesirable, but I think that it can be managed by collecting and restoring the clipboard before test execution. Mocking the clipboard behavior will leave little left to test, and they key thing to test here is if the Tk-based clipboard functionality actually works on all platforms.

At this stage I would prefer to simply skip this test on this version of MacOS with a `pytest.mark.skipif`.

I think this is best done with something like the following, but maybe there is a better way. Can post what you get from the following functions on MaxOS 11?

```python
>>> import platform
>>> platform.version()
'#38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020'
>>> platform.release()
'5.3.0-46-generic'
```

**Comment by ForeverWintr** [comment]
```
>>> platform.version()
'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64'
>>> platform.release()
'20.2.0'
``` 

Digging a bit further though, this seems to be an issue with homebrew's python installation, which should include an updated version of tk, but doesn't (on my system, anyway). It seems this behavior depends on how python is configured on a given system, more than the system itself.

A bigger concern for me is the global side effect of this test though. Restoring the clipboard after the test narrows the window in which a race condition occurs but doesn't eliminate it. Consider the case where a user cuts (`ctrl-x`) some important data after the test writes to the clipboard. The test will fail, then the 'restore' will overwrite the user's data. In my opinion, destructive system-level side effects from a unit test is bad practice.

**Comment by flexatone** [comment]
Thanks for these further comments.

First, I am not able to capture and restore to the clipboard via Tk, as Tk seems to always clear the clipboard if the clipboard is set within a process and the Tk `mainloop` is not entered:

https://stackoverflow.com/questions/9322070/unable-to-append-to-clipboard

This explains why the test does not leave the delimited string representation in the clipboard after the test: the clipboard is always empty. I do not see a way around this.

Second, I agree that a destructive system-level side effect is undesirable, but in this case it is only clipboard data, and only affects developers running StaticFrame tests, which is, I expect, a relatively small group. I will add a warning in the new Developer Guide in the documentation. I will also move this test to `test/integration` so it can be easily avoided when running unit tests.

Third, I think the absence of  Tk here is a temporary configuration issue with the homebrew install. As I wish to retain coverage on MacOS testing, and this issue is not encountered with GitHub Action servers, I will not try to skip this test for some versions of MacOS.

Thanks again for identifying this issue.

**Comment by flexatone** [comment]
https://static-frame.readthedocs.io/en/latest/developer.html
