### ISSUE TITLE
StoreZip sublcasses support multi-processing Frame creation

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#311]
Reading from a zip can only be done in series. All `StoreZip` subclasses, however, perform a two-part loading process: first reading in data to StringIO or BytesIO objects, then passing those off to `Frame` constructors. The second part, the `Frame` construction, can be multiprocessed to provide significant performance improvement when reading from zip stores with thousands of Frames.

This likely can be implemented in a general way for all StoreZip subclasses. This might also be efficient done in reverse for writing.

Engaging this feature will be optional and configured with the following new StoreConfig attributes (and defaults):

```python
read_max_workers: tp.Optional[int] = None
read_chunksize: int = 1
write_max_workers: tp.Optional[int] = None
write_chunksize: int = 1
```
A non-None `*_max_workers` value can be used to enable multiprocessing.

**Comment by chaburkland** [comment]
I just realized that placing these attributes on the `StoreConfig` class is a bit awkard, since a config can be both an "overall configuration", or a "per-item configuration" map.

Basically, in the case of a user treating their `store_config` as a map of label -> configuration, which multiprocessing_arguments do we use? The first observed? Do we fail if one label's config says `read_max_workers=10` and another label's config says `read_max_workers=None`?

**Comment by flexatone** [comment]
Yes, a similar issue came up for `label_encode` and `label_decode`, where it did not make sense for these to be different per table. The approach taken there might be appropriate here: always read these new parameters from the `default` of the `StoreConfigMap`, and then insure in `StoreConfigMap.__init__` that, if individual `StoreConfig` are provided, they are aligned for these parameters:

https://github.com/InvestmentSystems/static-frame/blob/29ce60384be66fdb538bfccc6853546cacb19d8d/static_frame/core/store.py#L216
