### ISSUE TITLE
loc_to_iloc can return strings.

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#323]
**Description**

This is minor, but I think it suggests something could be improved in `loc_to_iloc`. If I try to `iter_group` using a column that doesn't exist, I get a rather surprising error:

```python
list(sf.Frame.from_records([[1, 2, 3]]).iter_group('tom', axis=0))
# builtins.IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

A failure is expected here of course, but before I realized the cause I dug around a bit and noticed that `frame._columns.loc_to_iloc('tom')` returns 'tom'. Should it fail if the 'loc' it receives isn't in the Index?

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.4.0-66-generic-x86_64-with
sys.version        3.8.3 (default, Mar  2 2021, 12:44:27) [GCC 7.5.0]
static-frame       0.8.2
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.2
openpyxl           2.5.4
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>
```

**Example**

Provide code or pseudo code demonstrating how the feature might work, or how current behavior might be changed.

```python
list(sf.Frame.from_records([[1, 2, 3]]).iter_group('tom', axis=0))
```

**Comment by flexatone** [comment]
Thanks for posting this issue.

The issue here is that the columns Index created is an `IndexAutoFactory` style Index, which in other places in the code is described as `loc_is_iloc`: namely, we expect `loc` and `iloc` representations to be the same. For such indices, `loc_to_iloc` does no type checking, and simply passes through the input to be used as a selection, knowing that if it is not an `iloc` style selection, it will fail downstream.

The `loc_to_iloc` method could do a type check, but as a failure will occur if it is not a valid selection and we want `iloc` selection to be as fast as possible, it did not seem worth it.

What do you think?

**Comment by ForeverWintr** [comment]
I think that's an excellent solution!

**Comment by flexatone** [comment]
The new, public `loc_to_iloc` methods now raise if the key (or key components) are not found in the index. This will be part of the 0.8.3 release.

```python
>>> f = sf.Frame.from_records([[1, 2, 3]])                                                                                                 
>>> f.columns.loc_to_iloc('tom')                                                                                                           
KeyError: 'tom'
```
