### ISSUE TITLE
'bool' object has no attribute 'flags' when comparing IndexDates of different size

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#445]
**Description**

Comparing `Index`es of different sizes results in a boolean array; I think comparing `IndexDates` of different sizes probably should too. Currently it raises an AttributeError. 

**Example**

This raises an attribute error:

```python
import static_frame as sf
sf.IndexDate.from_date_range('2021-01-01', '2021-02-01') == sf.IndexDate.from_date_range('2021-01-02', '2021-02-01')
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.13.0-35-generic-x86_64-with
sys.version        3.8.12 (default, Mar 11 2022, 17:55:51) [GCC 7.5.0]
static-frame       0.8.36
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             0.18.0
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Thanks again for posting this issue.

While you did find an inconsistency, I think the particular case here should raise a `ValueError`, as the `IndexDate` being compared are of different sizes. Just like with all `Index`, we cannot provide a Boolean array as a result when comparing indices of different sizes because (a) the results are unlabelled and (b) it is ambiguous which size to use.

Investigating this, however, showed a few unhandled cases and invalid warnings that needed to be suppressed.

So with 0.8.37, we will see the following, which is consistent with all `Index`.

```python
>>> sf.Index(('a', 'b')) == sf.Index(('c', 'b'))
array([False,  True])
>>> sf.Index(('a', 'b')) == sf.Index(('c', 'b', 'a'))
ValueError: shape mismatch: objects cannot be broadcast to a single shape

>>> sf.IndexDate.from_date_range('2021-01-01', '2021-01-06') == sf.IndexDate.from_date_range('2021-01-01', '2021-01-06')
array([ True,  True,  True,  True,  True,  True])
>>> sf.IndexDate.from_date_range('2021-01-01', '2021-01-06') == sf.IndexDate.from_date_range('2021-01-02', '2021-01-06')
ValueError: operands could not be broadcast together
>>> sf.IndexDate.from_date_range('2021-01-01', '2021-01-06') == '2021-01-02'
array([False,  True, False, False, False, False])

**Comment by ForeverWintr** [comment]
I agree about raising a `ValueError`. I meant to suggest that `IndexDate` should behave the same as other indexes, and I mistakenly thought they returned arrays in this case.
