### ISSUE TITLE
Extended interfaces for assignment

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#464]
Either extend `assign`, or introduce a new interdace, to permit using operators on the target of assignment. 

Operators would be applied to the selection: 
`f2 = f.assign.loc['b'].apply(lambda s: s + 1)`
would be
`f2 = f.assign.loc['b'] + 1`

Thanks to @ForeverWintr for this suggestion.

We might also support a common case of needing element-wise function application:

`f2 = f.assign.loc['a':, 'b':].apply_element(lambda e: e.upper())`

Presently this can only be done as follows:

`f2 = f.assign.loc['a':, 'b':].apply(lambda f: f.iter_element().apply(lambda e: e.upper()))`

**Comment by gettodaze** [comment]
I like both of these! However I also do like how explicit ` f2 = f.assign.loc['b'].apply(lambda s: s + 1)` is. The alternative `f2 = f.assign.loc['b'] + 1` seems a little unintuitive that the `+ 1` is included in the `f.assign` move. What do you think? How would you compare that approach vs alternatives like the following?
- `f2 = sf.assign(f.loc['b'] + 1)`
- `f2 = f.assign(sf.Loc['b'] + 1)`

Also, would it support any expression taking in the appropriate type? For example:
```python
def myfunc(f: sf.Frame) -> sf.Frame:
   ...

f2 = myfunc(f.assign.loc['b':])
```

**Comment by ForeverWintr** [comment]
This feels different enough to warrant a new interface, IMO. I think there is an appealing conceptual simplicity in the idea that `assign` inserts the thing you provide into the frame, and `update` changes something that is already in the frame. 

Does there need to be overlapping functionality between the two interfaces? Maybe `update` does not implement `__call__`, but only overrides operators?

@gettodaze as we discussed I think `f2 = f.assign(sf.Loc['b'] + 1)` is an interesting idea, but I prefer `f.update.loc['b'] + 1` because I think it's a bit more intuitive, and overloading operators on `sf.Loc` seems complex. 

I think your point about `f.update.loc['b'] * 2 - 1` is good, however I imagine `update` as a conceptual analog to `*=`. When using `*=`, the right hand side is evaluated first, so `a *= 2 - 1` is the same as `a *= 1`. Users that want similar functionality with `update` could achieve it with parentheses: `f.update.loc['b'] * (2 - 1)`. But I agree that `f.update.loc['b'] * 2 - 1` could be confusing if it doesn't fail.

@flexatone can you remind me why we rejected overriding `__iadd__` etc.? The [docs](https://docs.python.org/3/reference/datamodel.html#object.__ior__) say "These methods should **attempt** to do the operation in-place (modifying self) and return the result (which could be, but does not have to be, self)." They don't outright forbid not modifying in place.

**Comment by ForeverWintr** [comment]
Answering my own question, of course using `+=` will attempt to assign to the `InterfaceGetItem`. :(

**Comment by flexatone** [comment]
Thanks, @ForeverWintr , for these comments. I will respond to your other points separately but given your point that this suggests a new interface, and given @gettodaze 's implicit suggestion that if we support binary operators, why not support more complex expressions, we might imagine a new interface that returns an object that can have multiple operations applied to it. The downside is `to_frame()` would be required to finally return a `Frame`. With such an approach we could do things like the following. 

`f2 = (f1.via_update.loc[2:, 'b'] * 2 - 1).to_frame()`

Again, the `to_frame()` reduces the conciseness of the original idea but is well established in SF with the `Batch`. 

Other containes (`Frame` or `Series`) could be incorporated in those expressions. 

`f2 = (f1.via_update.loc[2:, 'b'] * 2 - f3).to_frame()`

**Comment by chaburkland** [comment]
Just to quickly chime in, I am really concerned about the feature `f.assign[...] + 1`. I am not sure if it's seriously being considered, but I don't think this is a good idea.

The entire point of this request from @ForeverWintr (correct me if I'm wrong), is to add a simpler syntax for the following:
```python
frame = frame.assign.loc[...].apply(lambda s: ...)
```

However, the suggestions are not making this simpler!

```python
frame = (frame.via_update.loc[...] * 2 -1).to_frame()
```
is much more confusing (at least to me), than:

```python
frame = frame.assign.loc[...].apply(lambda s: s * 2 - 1)
```

I am sympathetic to the desire to add more simple syntax, but I want to state that I do feel the current syntax is completely acceptable and understandable. I fear we are attempting to re-invent a feature that already exists

**Comment by ForeverWintr** [comment]
I think we should be very aware of not adding redundant features, so I agree we should only do this if we can make it sufficiently simple, and confident it adds value.

@flexatone I think your suggestion amounts to the same thing as @gettodaze's second suggestion, FYI, except the object that can have multiple operations applied is `sf.Loc`, not `Frame/Series`.

@chaburkland  does `f.update[...] + 1` seem equally bad to you?

**Comment by ForeverWintr** [comment]
My original goal was to have a shortcut for the common move of making an update to an existing part of a frame. I think it's ok to sacrifice some flexibility for simplicity in this new interface. In fact, not supporting chained operators separates it further from `assign`, which makes it feel less redundant to me.

**Comment by chaburkland** [comment]
My concern with `f.update[...] + 1` is that it will be surprising to users when they chain. There's no way to enforce, or easily communicate to users that:

```python
frame = frame.update[column] + 2 * 3
```
Will add 2 to `frame[column]`, and then multiply the result by 3.

When I read that, I think the operation wants to add 2 to column 3 and _then multiply that same column by 3 after adding 2._

I feel very concerned this syntax will be consistently surprising, and not in a good way haha.

**Comment by ForeverWintr** [comment]
As a pedant I feel I should point out that your example actually adds 6 to `frame[column]`, but I realize that's beside the point. :smile: 

The more I think about this, the less concerned I am about chained operators being confusing. If you know that `frame.update` returns a frame (as all modifying operations do in StaticFrame), then I think the behavior makes sense.

**Comment by flexatone** [comment]
Thanks for all the discussion on this. At this point, I do not see a consensus or a strong-enough reason to create a new interface. While I am attracted to using operators on the target of assignment (or "update"), only being able to use one operator is more limiting than the corresponding lambda expression would be. Further, the additional syntax for that lambda is modest, and what the lambda is doing is quite readable. 

I will move forward with the new `apply_element()` and `apply_element_items()` methods as part of #465
