### ISSUE TITLE
`Series.from_items` to make data with `IndexHierarchy` indices

### ISSUE THREAD

**Issue by CrepeGoat** [InvestmentSystems/static-frame#49]
I want to make a `Series` with an `IndexHierarchy` index using `Series.from_items`. (I like `from_items` esp. for hard-coded data because it puts the indices directly next to their respective values, which is much easier to keep track of when reading & debugging code.)

For example, I want to do this:
```python
series = sf.Series.from_items([
    (('one', 1), 'hello'),
    (('two', 2), 'cya'),
])
```

What I get is this series:
```
<Series>
<Index>
('one', 1) hello
('two', 2) cya
<object>   <<U5>
```

But what I *want* is this series:
```
<Series>
<IndexHierarchy>
one              1        hello
two              2        cya
<object>         <object> <<U5>
```

So:
1. Is there an existing method for doing this?
2. If not, is there a method that would convert from the series I made into the series I want? (Something like the opposite of `reindex_flat`?) If there isn't, would it be worth implementing?
3. If "no" to all of the above, could you change `from_items` to interpret tuples as entries for an `IndexHierarchy`, without breaking anything else?

**Comment by flexatone** [comment]
Thanks for your thoughts on this issue; something similar has come up for me before and the best solution is still unresolved.

I am reluctant to automatically create an `IndexHierarchy` based on the type of the index labels given to any particular constructor, as (a) we want to be explicit in such moves and (b) there are legitimate cases for creating an index of tuples instead of an `IndexHierarchy`.

Something like this should work once the `Series` is created, but it does not presently (I will fix it shortly):

```python
series.reindex(sf.IndexHierarchy.from_labels(series.index))
```
However, this is far less efficient than getting the index you want from the original call to `from_items`.

One option that might help in a number of places (like working with an `IndexDate`) is to explicitly pass the Index constructor to the alternative constructor, so the call would look something like this:

```python
series = sf.Series.from_items([
    (('one', 1), 'hello'),
    (('two', 2), 'cya'),
    ], index_constructor=IndexHierarchy.from_labels)
```

What do you think about this approach?

**Comment by flexatone** [comment]
I have taken the approach of exposing `index_constructor` as an argument, here and elsewhere, to permit using `IndexHierarchy` or `IndexDate`-style indices in these sorts of cases. There are other interfaces that will benefit from this approach as well.

So for now, you can do the following:

```python
>>> series = sf.Series.from_items([
...     (('one', 1), 'hello'),
...     (('two', 2), 'cya'),
...     ], index_constructor=sf.IndexHierarchy.from_labels)
>>> series
<Series>
<IndexHierarchy>
one              1        hello
two              2        cya
<object>         <object> <<U5>
```
